# Generated by Django 3.1.3 on 2020-11-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='author',
        ),
    ]
